# Generated by Django 3.1.5 on 2021-01-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nilai',
            field=models.IntegerField(default='', max_length=250),
        ),
    ]
