# Generated by Django 3.1.5 on 2021-01-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210116_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='nilai',
            field=models.IntegerField(default=''),
        ),
    ]
